/** @type {import('next').NextConfig} */

const { i18n } = require('./next-i18next.config')

const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  i18n: i18n,

  images: {
    domains: ['localhost', '150.230.144.136'],
  },

  env: {
    APPWRITE_APP_ENDPOINT: process.env.APPWRITE_APP_ENDPOINT,
    APPWRITE_PROJECT_ID: process.env.APPWRITE_PROJECT_ID,
    APPWRITE_API_KEY_USERS_READ: process.env.APPWRITE_API_KEY_USERS_READ,
    APPWRITE_TEAMS_DATABASE_ID: process.env.APPWRITE_TEAMS_DATABASE_ID,
    APPWRITE_LAYOUTS_COLLECTION_ID: process.env.APPWRITE_LAYOUTS_COLLECTION_ID,
    APPWRITE_BOARDS_COLLECTION_ID: process.env.APPWRITE_BOARDS_COLLECTION_ID,
    APPWRITE_BACKGROUNDS_COLLECTION_ID: process.env.APPWRITE_BACKGROUNDS_COLLECTION_ID,

    APPWRITE_BOARDS_DATABASE_ID: process.env.APPWRITE_BOARDS_DATABASE_ID,
    APPWRITE_COLUMNS_COLLECTION_ID: process.env.APPWRITE_COLUMNS_COLLECTION_ID,
    APPWRITE_CARDS_COLLECTION_ID: process.env.APPWRITE_CARDS_COLLECTION_ID,

    APPWRITE_CONFERENCES_DATABASE_ID: process.env.APPWRITE_CONFERENCES_DATABASE_ID,
    APPWRITE_CHANNELS_COLLECTION_ID: process.env.APPWRITE_CHANNELS_COLLECTION_ID,

    APPWRITE_WHITEBOARDS_DATABASE_ID: process.env.APPWRITE_WHITEBOARDS_DATABASE_ID,
    APPWRITE_WHITEBOARDS_COLLECTION_ID: process.env.APPWRITE_WHITEBOARDS_COLLECTION_ID,

    SAMEDI_LIVE_ACCESS_KEY: process.env.SAMEDI_LIVE_ACCESS_KEY,
    SAMEDI_LIVE_SECRET_KEY: process.env.SAMEDI_LIVE_SECRET_KEY,
    SAMEDI_TOKEN_ENDPOINT: process.env.SAMEDI_TOKEN_ENDPOINT,


  }
}

module.exports = nextConfig
