import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import Footer from "../components/common/Footer";

export default function Home() {
  const { t } = useTranslation("common");

  return (
    <>
      <Head>
        <title>Samedi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen">
        <section
          id="hero"
          className="flex flex-col items-center justify-center min-h-screen py-4 bg-gradient-to-b from-[#E5B8F4]/50 to-white"
        >
          <h1 className="text-8xl text-gray-900 font-thin">Samedi</h1>
          <h2 className="mt-3 text-xl text-gray-700 font-thin">
            {t("index.hero.subtitle")}
            <a className="text-[#2D033B] font-normal">
              {t("index.hero.business")}
            </a>
          </h2>
          <Link href="#about">
            <button className="mt-6 px-5 py-3 bg-gray-100 text-gray-800 font-semibold rounded-md hover:bg-[#2D033B] hover:text-white transition duration-300 shadow-lg">
              {t("index.hero.button")}
            </button>
          </Link>
        </section>
        <section
          id="about"
          className="flex flex-col min-h-screen items-center py-4"
        >
          <h1 className="text-8xl text-gray-800 font-thin mb-12">
            {t("index.about.title")}
          </h1>
          <div className="flex flex-wrap">
            <div className="grow-0 shrink-0 basis-auto w-full lg:w-7/12">
              <div className="h-full rounded-lg p-6 lg:pl-12 text-gray-800 flex items-center text-center lg:text-left">
                <div className="lg:pl-12 flex-col items-center w-full">
                  <h2 className="text-3xl font-bold mb-6">
                    {t("index.about.features.first.label")}
                  </h2>
                  <p className="mb-6 pb-2 lg:pb-0">
                    {t("index.about.features.first.description")}
                  </p>
                  <button
                    type="button"
                    className="inline-block px-7 py-3 border-2 border-gray-800 text-gray-800 font-medium text-sm leading-snug uppercase rounded-full hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out"
                    data-mdb-ripple="true"
                    data-mdb-ripple-color="light"
                  >
                    {t("index.about.readMore")}
                  </button>
                </div>
              </div>
            </div>
            <div className="grow-0 shrink-0 basis-auto w-full lg:w-5/12 mb-12 lg:mb-0">
              <div className="flex lg:py-12 w-full items-center">
                <Image
                  src="/images/stock/bus1.svg"
                  height={500}
                  width={500}
                  className="w-full rounded-lg z-10 mx-4"
                  alt=""
                />
              </div>
            </div>
          </div>
          <div className="flex flex-wrap">
            <div className="grow-0 shrink-0 basis-auto w-full lg:w-5/12 mb-12 lg:mb-0 lg:order-first order-last">
              <div className="flex lg:py-12">
                <Image
                  src="/images/stock/bus2.svg"
                  height={500}
                  width={500}
                  className="w-full rounded-lg z-10 mx-4"
                  alt=""
                />
              </div>
            </div>
            <div className="grow-0 shrink-0 basis-auto w-full lg:w-7/12">
              <div className="h-full rounded-lg p-6 lg:pl-12 text-gray-800 flex items-center text-center lg:text-left">
                <div className="lg:pl-12 flex-col items-center w-full">
                  <h2 className="text-3xl font-bold mb-6 ">
                    {t("index.about.features.second.label")}
                  </h2>
                  <p className="mb-6 pb-2 lg:pb-0">
                    {t("index.about.features.second.description")}
                  </p>
                  <button
                    type="button"
                    className="inline-block px-7 py-3 border-2 border-gray-800 text-gray-800 font-medium text-sm leading-snug uppercase rounded-full hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out"
                    data-mdb-ripple="true"
                    data-mdb-ripple-color="light"
                  >
                    {t("index.about.readMore")}
                  </button>
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-wrap">
            <div className="grow-0 shrink-0 basis-auto w-full lg:w-7/12">
              <div className="h-full rounded-lg p-6 lg:pl-12 text-gray-800 flex items-center text-center lg:text-left">
                <div className="lg:pl-12 flex-col items-center w-full">
                  <h2 className="text-3xl font-bold mb-6">
                    {t("index.about.features.third.label")}
                  </h2>
                  <p className="mb-6 pb-2 lg:pb-0">
                    {t("index.about.features.third.description")}
                  </p>
                  <button
                    type="button"
                    className="inline-block px-7 py-3 border-2 border-gray-800 text-gray-800 font-medium text-sm leading-snug uppercase rounded-full hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out"
                    data-mdb-ripple="true"
                    data-mdb-ripple-color="light"
                  >
                    {t("index.about.readMore")}
                  </button>
                </div>
              </div>
            </div>
            <div className="grow-0 shrink-0 basis-auto w-full lg:w-5/12 mb-12 lg:mb-0">
              <div className="flex lg:py-12">
                <Image
                  src="/images/stock/bus3.webp"
                  height={30}
                  width={300}
                  className="w-full rounded-lg z-10 mx-4"
                  alt=""
                />
              </div>
            </div>
          </div>
        </section>
        <section
          id="pricing"
          className="flex flex-col items-center justify-center min-h-screen py-4"
        ></section>
      </main>

      <Footer />
    </>
  );
}

export async function getStaticProps({ locale }: any) {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? 'en', ["common"])),
    },
  };
}